remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Cardiosomnography:\nECG-only sleep staging"
description: Expert-level sleep staging using an ECG-only neural network
