remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: [ECG-only based sleep staging]
description:
  [
    Expert-level sleep staging using an electrocardiography-only feed-forward neural network,
  ]
